version: '3.7'

services:
  gitea:
    restart: always
    image: whatwewant/gitea:${SERVICE_GITEA_IMAGE_VERSION}
    ports:
      - 127.0.0.1:${SERVICE_GITEA_PORT}:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_DATA}:/data

networks:
  default:
    external: true
    name: compose-ingress
